### ISSUE TITLE
mnisten error

### ISSUE THREAD

**Issue by yyfsss** [nyanp/mnisten#11]
When i use mnisten master to convert my image. It always shows that no images. It seems that it cant recognition my own images. When i use opencv to convert my color to the vec_t. Caffe also says no images and drop out of the vector.

here is the command when i use mnisten :
--mnisten -d E:\train3\ -o prefix -s 32x24
here is the error messages:
0:cat 0images
1:dog 0images
2:horse 0images
error:total images are less than num_tests
my images format are .jpg format

**Comment by yyfsss** [comment]
and can you give me a example on how to use Caffe to train my own color images which include the image converttion .

**Comment by yyfsss** [comment]
@nyanp

**Comment by yyfsss** [comment]
When I use debug model It cannot recognize my images. but When I use release model It works.

**Comment by nyanp** [comment]
@yyfsss
What debug/release model means? Did you solved the ploblem?

**Comment by yyfsss** [comment]
@nyanp  Yes The problem has been solved. It means I use Vs Dubug model build the mnisten but it cannot recognize my inages. When I use Vs Release model to bulid the mnisten It works.
