### ISSUE TITLE
Build error on Ubuntu 14.04

### ISSUE THREAD

**Issue by Kongsea** [nyanp/mnisten#9]
When I build the mnisten on Ubuntu system, it gives the following error:

```
g++ -Wall -O2 -lboost_filesystem-mt -std=c++0x -o mnisten src/main.cpp
/usr/bin/ld: cannot find -lboost_filesystem-mt
collect2: error: ld returned 1 exit status
make: *** [mnisten] Error 1
```

I have already installed the boost library.
Could you please tell me the reason and the solution to this issue?
Thank you very much.

**Comment by kristoffzoghbi** [comment]
I was having the same error, fixed it with:

apt-get install libboost-all-dev

**Comment by gxstudy** [comment]
I am having the same problem, but my libboost-all-dev is already the newest version, any idea of how to solve it? Thanks a lot. @nyanp @kristoffzoghbi @Kongsea
